#!/bin/sh

ghdl -a --workdir=work src/out_gen.vhd ;
ghdl -a --workdir=work tbs/tb_out_gen.vhd ;
ghdl -r --workdir=work tb_out_gen --vcd=out_gen.gtkwave ;
gtkwave out_gen.gtkwave ;

# ghdl -a --workdir=work src/pc.vhd ;
# ghdl -a --workdir=work tbs/tb_pc.vhd ;
# ghdl -r --workdir=work tb_pc --vcd=pc.gtkwave ;
# gtkwave pc.gtkwave ;

